on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        with:
          path: ~/.racket
          key: ${{ runner.os }}-raco-${{ hashFiles('**/info.rkt') }}
      - uses: Bogdanp/setup-racket@v0.6
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'regular'
          version: 'current'
      # Typed Racket Hacks prints to STDOUT causing exit code 1. Let's just force success.
      - run: raco pkg install --auto */ || true
      # If we have a cache hit, the above will link the current working directory as the
      # package. But that will not be compiled. Therefore, we have to setup.
      - run: raco setup corpse-reviver
      - uses: GabrielBB/xvfb-action@v1.0
        with:
          # Stop the tests after 30 minutes.
          run: raco test -x --drdr --timeout 1800 corpse-reviver-lib/private corpse-reviver-lib/main.rkt
